Feature task estimation
EtiennePASSOT/SQA-assignment-group9 pull request #20
Opened 2020-03-31 17:42 UTC by 4kh

Here is the task estimation part of the documenation
Don't hesite to comment or propose some additional content

2020-03-31 17:44 UTC, valotg approved these changes

2020-03-31 17:49 UTC, Arakhaa commented on README.md
> +
I like this to do list

2020-03-31 17:53 UTC, Arakhaa commented on README.md
> +
Maybe add an image to understand the "hierachy" in SCRUM methodology ?

2020-03-31 17:55 UTC, Arakhaa commented on README.md
> +The Scrum life cycle is punctuated by iterations of a few weeks, the sprints.
Thanks to our Business Modeling lecture, you could specify the time of sprint ? (between 5 days to 2 weeks in general)

2020-03-31 17:58 UTC, Arakhaa requested changes
Take a look at my comments before merging

2020-03-31 21:13 UTC, EtiennePASSOT approved these changes

2020-04-01 00:41 UTC, Arakhaa commented
Thanks for the changes

2020-04-01 00:41 UTC, merged